db:
  image: postgres
  container_name: db
  restart: always
  environment:
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: admin
    POSTGRES_DB: hn_parser

hn_parser:
  build: .
  dockerfile: Dockerfile
  links:
    - db
  ports:
    - "8000:8000"
  environment:
    PORT: 8000
    DB_HOST: db
    PGPASSWORD: admin
